//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTesisPagoServicios.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppTesisPagoServicios.Recursos.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Consulta/ListaConsultas.
        /// </summary>
        internal static string Colsulta_ListaConsultas {
            get {
                return ResourceManager.GetString("Colsulta_ListaConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Consulta/ListaConsultasPorFecha.
        /// </summary>
        internal static string Consulta_ListaConsultasPorFecha {
            get {
                return ResourceManager.GetString("Consulta_ListaConsultasPorFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Consulta/RealizarConsulta.
        /// </summary>
        internal static string Consulta_RealizaConsulta {
            get {
                return ResourceManager.GetString("Consulta_RealizaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Pago/ListaPago.
        /// </summary>
        internal static string Pago_ListaPago {
            get {
                return ResourceManager.GetString("Pago_ListaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Pago/ListaPagoFechas.
        /// </summary>
        internal static string Pago_ListaPagoFechas {
            get {
                return ResourceManager.GetString("Pago_ListaPagoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Pago/RealizarPago.
        /// </summary>
        internal static string Pago_RealizarPago {
            get {
                return ResourceManager.GetString("Pago_RealizarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Parametrizacion/ActualizarParametrizacion.
        /// </summary>
        internal static string Parametrizacion_ActualizarUsuario {
            get {
                return ResourceManager.GetString("Parametrizacion_ActualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Parametrizacion/GuardarParametrizacion.
        /// </summary>
        internal static string Parametrizacion_GuardarUsuario {
            get {
                return ResourceManager.GetString("Parametrizacion_GuardarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Parametrizacion/ListaParametrizacion.
        /// </summary>
        internal static string Parametrizacion_ListarUsuarios {
            get {
                return ResourceManager.GetString("Parametrizacion_ListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Servicio/ActualizarServicio.
        /// </summary>
        internal static string Servicio_ActualizarServicio {
            get {
                return ResourceManager.GetString("Servicio_ActualizarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Servicio/EliminarServicio.
        /// </summary>
        internal static string Servicio_EliminarServicio {
            get {
                return ResourceManager.GetString("Servicio_EliminarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Servicio/GuardarServicio.
        /// </summary>
        internal static string Servicio_GuardarServicio {
            get {
                return ResourceManager.GetString("Servicio_GuardarServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Servicio/ListaServicios.
        /// </summary>
        internal static string Servicio_ListarServicios {
            get {
                return ResourceManager.GetString("Servicio_ListarServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /ServicioUsuario/ActualizarServicioUsuario.
        /// </summary>
        internal static string ServicioUsuario_ActualizarServicioUsuario {
            get {
                return ResourceManager.GetString("ServicioUsuario_ActualizarServicioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /ServicioUsuario/EliminarServicioUsuario.
        /// </summary>
        internal static string ServicioUsuario_EliminarServicioUsuario {
            get {
                return ResourceManager.GetString("ServicioUsuario_EliminarServicioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /ServicioUsuario/GuardarServicioUsuario.
        /// </summary>
        internal static string ServicioUsuario_GuardarServicioUsuario {
            get {
                return ResourceManager.GetString("ServicioUsuario_GuardarServicioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /ServicioUsuario/ListaServicioUsuario.
        /// </summary>
        internal static string ServicioUsuario_ListarServiciosUsuarios {
            get {
                return ResourceManager.GetString("ServicioUsuario_ListarServiciosUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoPago/ActualizarTipoPago.
        /// </summary>
        internal static string TipoPago_ActualizarTipoPago {
            get {
                return ResourceManager.GetString("TipoPago_ActualizarTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoPago/EliminarTipoPago.
        /// </summary>
        internal static string TipoPago_EliminarTipoPago {
            get {
                return ResourceManager.GetString("TipoPago_EliminarTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoPago/GuardarTipoPago.
        /// </summary>
        internal static string TipoPago_GuardarTipoPago {
            get {
                return ResourceManager.GetString("TipoPago_GuardarTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoPago/ListaTipoPagos.
        /// </summary>
        internal static string TipoPago_ListarTipoPagos {
            get {
                return ResourceManager.GetString("TipoPago_ListarTipoPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoReferencia/ActualizarTipoReferencia.
        /// </summary>
        internal static string TipoReferencia_ActualizarTipoReferencia {
            get {
                return ResourceManager.GetString("TipoReferencia_ActualizarTipoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoReferencia/EliminarTipoReferencia.
        /// </summary>
        internal static string TipoReferencia_EliminarTipoReferencia {
            get {
                return ResourceManager.GetString("TipoReferencia_EliminarTipoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoReferencia/GuardarTipoReferencia.
        /// </summary>
        internal static string TipoReferencia_GuardarTipoReferencia {
            get {
                return ResourceManager.GetString("TipoReferencia_GuardarTipoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoReferencia/ListaTipoReferencias.
        /// </summary>
        internal static string TipoReferencia_ListarTipoReferencia {
            get {
                return ResourceManager.GetString("TipoReferencia_ListarTipoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoServicio/ActualizarTipoServicio.
        /// </summary>
        internal static string TipoServicio_ActualizarTipoServicio {
            get {
                return ResourceManager.GetString("TipoServicio_ActualizarTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoServicio/EliminarTipoServicio.
        /// </summary>
        internal static string TipoServicio_EliminarTipoServicio {
            get {
                return ResourceManager.GetString("TipoServicio_EliminarTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoServicio/GuardarTipoServicio.
        /// </summary>
        internal static string TipoServicio_GuardarTipoServicio {
            get {
                return ResourceManager.GetString("TipoServicio_GuardarTipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /TipoServicio/ListaTipoServicios.
        /// </summary>
        internal static string TipoServicio_ListarTipoServicios {
            get {
                return ResourceManager.GetString("TipoServicio_ListarTipoServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/ActualizarContraseniaUsuario.
        /// </summary>
        internal static string Usuario_ActualizarContraseniaUsuario {
            get {
                return ResourceManager.GetString("Usuario_ActualizarContraseniaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/ActualizarUsuario.
        /// </summary>
        internal static string Usuario_ActualizarUsuario {
            get {
                return ResourceManager.GetString("Usuario_ActualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/EliminarUsuario.
        /// </summary>
        internal static string Usuario_EliminarUsuario {
            get {
                return ResourceManager.GetString("Usuario_EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/EnviarOTP?username=.
        /// </summary>
        internal static string Usuario_EnviarOTP {
            get {
                return ResourceManager.GetString("Usuario_EnviarOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/GuardarUsuario.
        /// </summary>
        internal static string Usuario_GuardarUsuario {
            get {
                return ResourceManager.GetString("Usuario_GuardarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/ListaUsuarios.
        /// </summary>
        internal static string Usuario_ListarUsuarios {
            get {
                return ResourceManager.GetString("Usuario_ListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/LoginUsuario.
        /// </summary>
        internal static string Usuario_LoginUsuario {
            get {
                return ResourceManager.GetString("Usuario_LoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Usuario/ValidaOTP.
        /// </summary>
        internal static string Usuario_ValidarOTP {
            get {
                return ResourceManager.GetString("Usuario_ValidarOTP", resourceCulture);
            }
        }
    }
}
